name: docker build and publish

on:
  create:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=,format=short
            type=semver,pattern={{version}}

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: checkout infra repository
        uses: actions/checkout@v2
        with:
          repository: joaofnds/foobar-infra
          path: foobar-infra
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update staging image version
        uses: fjogeleit/yaml-update-action@master
        env:
          VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        with:
          workDir: foobar-infra
          repository: joaofnds/foobar-infra
          masterBranchName: main
          valueFile: foo-staging/deployment.yaml
          propertyPath: spec.template.spec.containers.0.image
          value: ${{ env.VERSION }}
          branch: main
          targetBranch: main
          createPR: true
          message: Update foo-staging image to ${{ env.VERSION }}
          title: Bump foo-staging version to ${{ env.VERSION }}
          token: ${{ secrets.GH_TOKEN }}
